import { t } from '@/shared/i18n'

export const platformPagesContent = t({
  en: {
    common: {
      source: 'Source',
      all: 'All',
      previous: 'Previous',
      restart: 'Start over',
      copy: 'Copy result link',
      copied: 'Link copied',
      question: 'Question',
      of: 'of',
      verdict: 'your verdict',
      pillars: 'readiness across four pillars',
      drivers: 'what drove this verdict',
      instead: 'what to do instead',
      recheck: 're-check when',
      phases: 'how this path typically unfolds',
      watchouts: 'watchouts',
      firstStep: 'recommended first step',
      book: 'Book a discovery call',
      reminder: 'Add a 6-month reminder (.ics)',
      sampleNotice:
        'Example result for a fictional company — your answers will produce your own verdict.',
    },
    readiness: {
      badges: ['Free · No signup', '7 questions · 3 minutes'],
      heroText:
        'Seven plain questions about your business. One clear verdict with the path that fits — or an honest “not yet” and what to do instead.',
      primary: 'Get my verdict',
      sample: 'See a sample result',
      privacy: 'Nothing is sent anywhere — the verdict is computed in your browser.',
      verdictsLabel: 'One of five verdicts, instantly',
      assessmentLabel: 'Tokenization readiness assessment',
      methodologyLabel: 'How the scoring works',
      methodologyTitle: 'Four pillars, scored transparently.',
      methodologyItems: [
        ['Asset', 'Something worth digitizing'],
        ['Business', 'Revenue and clean records'],
        ['Capital', 'A goal this instrument fits'],
        ['Execution', 'Realistic timeline'],
      ],
      fullMethodology: 'Full methodology',
      definition: 'What “tokenization” means here',
      faq: 'FAQ',
    },
    cases: {
      title: 'Tokenization Case Library — Real Deals, Real Numbers',
      description:
        'BlackRock, Franklin Templeton, Figure, Apollo, JPMorgan: what serious institutions actually tokenized, at what scale. Sourced, updated, no email wall.',
      badges: ['Sourced', 'Updated quarterly'],
      headline:
        'The largest names in finance already run digital-asset programs.',
      lead:
        'Funds, loans, stocks, and real estate — with the scale of each program. Every number links to its source.',
      scaleLabel: 'Not BlackRock? Good.',
      scaleText:
        'You do not need their budget. The same infrastructure is sold as a service. The institutions above prove the approach works; mid-size businesses rent it.',
      ctaTitle: 'Could your business be next?',
      readiness: 'Get your verdict in 3 minutes',
      contact: 'Talk to the team',
      filterCta: 'Check my fit',
    },
    ai: {
      title: 'Tokenomics AI — Your Token Model, Built in 48h',
      description:
        'AI drafts your token model; the 8Blocks scoring engine flags structural risks and tunes it. Model plus data-room PDF in 48 hours. From $299. Early access.',
      badges: ['Early access', 'From $299', '48h turnaround'],
      headline: 'Your token model.',
      accent: 'Investor-ready in 48 hours.',
      lead:
        'AI drafts allocations and vesting. The 8Blocks scoring engine flags structural risks and refines the model. You get the refined design and a report for your data room.',
      request: 'Request early access',
      how: 'How it will work',
      deliverablesLabel: 'What you get',
      deliverables: [
        ['Refined model', '8 buckets + vesting, tuned against category benchmarks'],
        [
          'Structure Score',
          'Shows where your supply structure creates sell pressure, judged against launches like yours',
        ],
        ['Investor PDF', 'Branded report ready for your data room'],
      ],
      compareLabel: 'Free calculator vs Sprint',
      freeTitle: 'FREE · TOKEN LAB',
      sprintTitle: 'SPRINT · $299 AT LAUNCH',
      freeItems: [
        'You model everything yourself',
        'Structure Score against generic archetype norms',
        'Self-serve PDF export',
      ],
      sprintItems: [
        'AI + 8Blocks methodology build the model for you',
        'Tuned to your category, stage and committed allocations',
        'Investor-ready written report, delivered in 48h',
      ],
      calculator: 'Open the calculator',
      waitlist: 'Join the waitlist',
      limited: 'Limited spots. No payment now.',
      limitedText:
        'Tell us about the project — we will reach out when a spot opens.',
      modalTitle: 'AI Token Model Sprint',
      modalEyebrow: 'EARLY ACCESS · $299 AT LAUNCH',
      success: 'You are on the list',
      successText:
        'Nothing is charged now. We will reach out when a spot opens. Meanwhile, the calculator is free.',
      sending: 'Sending…',
      error: 'Something went wrong. Try again.',
      projectPlaceholder: 'Project name *',
      emailPlaceholder: 'you@project.com *',
      goalPlaceholder: 'What do you need this for? *',
      stagePlaceholder: 'Stage…',
      heardPlaceholder: 'How did you hear…',
      disclaimer:
        'Early access request only — no payment now, no delivery promises. Not investment advice.',
      simulatedLabel: 'simulated',
      simulationDisclaimer:
        'Illustration of the planned product flow — not a live model run.',
      goals: [
        'Prepare an investor round',
        'Get an expert check of my design',
        'See what my token could look like',
        'Other',
      ],
      stages: ['Pre-TGE', 'Post-TGE', 'Exploring'],
      heard: [
        'Google search',
        'AI assistants (ChatGPT, Claude...)',
        'X / Twitter',
        'Telegram',
        'Referral',
        'Other',
      ],
      demoSteps: [
        ['You describe the project', 'Name, sector, stage, goal — 2 minutes.'],
        ['AI asks what matters', 'A short dialogue fills the gaps a form cannot.'],
        ['Model is generated', 'Allocations + vesting vs category benchmarks.'],
        ['You get the package', 'Refined model · Structure Score · investor PDF.'],
      ],
    },
    benchmarks: {
      title: 'Token Vesting & Allocation Benchmarks (2026)',
      description:
        'How much supply goes to team, investors, community and treasury — and how it vests. Compiled from published research with sources.',
      badges: [
        'Compiled from published research',
        'No email wall',
        'Updated July 2026',
      ],
      headline: 'Token Vesting & Allocation Benchmarks',
      lead:
        'How much supply top launches gave the team, investors, and community — and how fast it unlocked. Set numbers you can defend, with published sources throughout.',
      projectsCount: '22 launches · re-verified July 2026',
      categoryLabel: 'By category: what top projects actually did',
      categoryLead:
        'Pick your category, see what leading projects published, and load any structure into the calculator as a starting point.',
      categoryDefinition: 'What defines this category',
      insiderShare: 'average insider share',
      audited: 'Audited by 8Blocks',
      publicAudits: 'Full public audits',
      readAudit: 'Read the public audit',
      allocationLabel: 'Allocation benchmarks by bucket',
      contextSources: 'Context & sources',
      calculatorText:
        'Check your own numbers in the calculator. The Structure Score grades them against launches like yours.',
      calculator: 'Open the calculator',
      vestingLabel: 'Vesting norms',
      trendsLabel: 'What the market data shows',
      faq: 'FAQ',
      methodology: 'Methodology and limitations',
      openCalculator: 'Open in calculator',
      dataNote:
        'Allocations reconstructed from official docs and public data platforms, re-verified July 2026.',
    },
  },
  ru: {
    common: {
      source: 'Источник',
      all: 'Все',
      previous: 'Назад',
      restart: 'Начать заново',
      copy: 'Скопировать ссылку на результат',
      copied: 'Ссылка скопирована',
      question: 'Вопрос',
      of: 'из',
      verdict: 'ваш вердикт',
      pillars: 'готовность по четырём направлениям',
      drivers: 'что определило вердикт',
      instead: 'что сделать вместо этого',
      recheck: 'когда вернуться к проверке',
      phases: 'как обычно развивается этот сценарий',
      watchouts: 'на что обратить внимание',
      firstStep: 'рекомендуемый первый шаг',
      book: 'Записаться на ознакомительный созвон',
      reminder: 'Добавить напоминание через 6 месяцев (.ics)',
      sampleNotice:
        'Пример результата для вымышленной компании — ваши ответы сформируют собственный вердикт.',
    },
    readiness: {
      badges: ['Бесплатно · Без регистрации', '7 вопросов · 3 минуты'],
      heroText:
        'Семь простых вопросов о бизнесе. Один понятный вердикт с подходящим путём — или честное «пока рано» и альтернативы.',
      primary: 'Получить вердикт',
      sample: 'Посмотреть пример',
      privacy: 'Данные никуда не отправляются — результат рассчитывается в браузере.',
      verdictsLabel: 'Один из пяти вердиктов — сразу',
      assessmentLabel: 'Оценка готовности к токенизации',
      methodologyLabel: 'Как работает оценка',
      methodologyTitle: 'Четыре направления с прозрачным скорингом.',
      methodologyItems: [
        ['Актив', 'Есть что перевести в цифровой инструмент'],
        ['Бизнес', 'Выручка и чистые документы'],
        ['Капитал', 'Цель подходит инструменту'],
        ['Реализация', 'Реалистичные сроки'],
      ],
      fullMethodology: 'Полная методология',
      definition: 'Что здесь означает «токенизация»',
      faq: 'Вопросы и ответы',
    },
    cases: {
      title: 'Библиотека кейсов токенизации — реальные сделки и цифры',
      description:
        'BlackRock, Franklin Templeton, Figure, Apollo и JPMorgan: что токенизируют крупные институты и в каком масштабе.',
      badges: ['Со ссылками на источники', 'Обновляется ежеквартально'],
      headline:
        'Крупнейшие финансовые компании уже развивают программы цифровых активов.',
      lead:
        'Фонды, кредиты, акции и недвижимость — с масштабом каждой программы и ссылками на первоисточники.',
      scaleLabel: 'Вы не BlackRock? Отлично.',
      scaleText:
        'Их бюджет не нужен. Та же инфраструктура продаётся как сервис. Институты доказали работоспособность подхода, а средний бизнес может арендовать его.',
      ctaTitle: 'Ваш бизнес может быть следующим?',
      readiness: 'Получить вердикт за 3 минуты',
      contact: 'Поговорить с командой',
      filterCta: 'Проверить свой кейс',
    },
    ai: {
      title: 'Tokenomics AI — модель токена за 48 часов',
      description:
        'AI создаёт черновик модели, а скоринг А8А9 выявляет структурные риски и помогает доработать результат.',
      badges: ['Ранний доступ', 'От $299', 'Готовность за 48 часов'],
      headline: 'Ваша модель токена.',
      accent: 'Готова для инвесторов за 48 часов.',
      lead:
        'AI создаёт аллокации и вестинг. Скоринг А8А9 выявляет структурные риски и дорабатывает модель. Вы получаете дизайн и отчёт для data room.',
      request: 'Запросить ранний доступ',
      how: 'Как это будет работать',
      deliverablesLabel: 'Что вы получите',
      deliverables: [
        ['Доработанная модель', '8 бакетов и вестинг с учётом отраслевых бенчмарков'],
        ['Structure Score', 'Показывает структурные риски предложения и давление продаж'],
        ['PDF для инвесторов', 'Брендированный отчёт, готовый для data room'],
      ],
      compareLabel: 'Бесплатный калькулятор и Sprint',
      freeTitle: 'БЕСПЛАТНО · TOKEN LAB',
      sprintTitle: 'SPRINT · $299 НА СТАРТЕ',
      freeItems: [
        'Вы самостоятельно собираете модель',
        'Structure Score по общим отраслевым нормам',
        'Самостоятельный экспорт PDF',
      ],
      sprintItems: [
        'AI и методология А8А9 собирают модель за вас',
        'Настройка под категорию, стадию и обязательства',
        'Письменный отчёт для инвесторов за 48 часов',
      ],
      calculator: 'Открыть калькулятор',
      waitlist: 'Встать в лист ожидания',
      limited: 'Количество мест ограничено. Оплата сейчас не нужна.',
      limitedText:
        'Расскажите о проекте — мы свяжемся, когда появится место.',
      modalTitle: 'AI Token Model Sprint',
      modalEyebrow: 'РАННИЙ ДОСТУП · $299 НА СТАРТЕ',
      success: 'Вы в списке',
      successText:
        'Сейчас ничего не списывается. Мы свяжемся, когда появится место. Калькулятор пока доступен бесплатно.',
      sending: 'Отправляем…',
      error: 'Не удалось отправить. Попробуйте ещё раз.',
      projectPlaceholder: 'Название проекта *',
      emailPlaceholder: 'you@project.com *',
      goalPlaceholder: 'Для чего вам это нужно? *',
      stagePlaceholder: 'Стадия…',
      heardPlaceholder: 'Как вы о нас узнали…',
      disclaimer:
        'Только заявка на ранний доступ — без оплаты и обещаний срока поставки. Не является инвестиционной рекомендацией.',
      simulatedLabel: 'симуляция',
      simulationDisclaimer:
        'Иллюстрация планируемого процесса продукта — не запуск реальной модели.',
      goals: [
        'Подготовить раунд инвестиций',
        'Получить экспертную проверку дизайна',
        'Увидеть возможную модель токена',
        'Другое',
      ],
      stages: ['До TGE', 'После TGE', 'Исследуем возможность'],
      heard: [
        'Поиск Google',
        'AI-ассистенты (ChatGPT, Claude...)',
        'X / Twitter',
        'Telegram',
        'Рекомендация',
        'Другое',
      ],
      demoSteps: [
        ['Вы описываете проект', 'Название, сектор, стадия и цель — 2 минуты.'],
        ['AI задаёт важные вопросы', 'Короткий диалог закрывает пробелы формы.'],
        ['Создаётся модель', 'Аллокации и вестинг сравниваются с бенчмарками.'],
        ['Вы получаете пакет', 'Модель · Structure Score · PDF для инвесторов.'],
      ],
    },
    benchmarks: {
      title: 'Бенчмарки аллокаций и вестинга токенов (2026)',
      description:
        'Сколько токенов получают команда, инвесторы и сообщество и как устроен их вестинг. Данные из опубликованных исследований.',
      badges: [
        'По опубликованным исследованиям',
        'Без email-гейта',
        'Обновлено в июле 2026',
      ],
      headline: 'Бенчмарки аллокаций и вестинга токенов',
      lead:
        'Сколько токенов ведущие проекты выделяли команде, инвесторам и сообществу и с какой скоростью они разблокировались.',
      projectsCount: '22 запуска · перепроверено в июле 2026',
      categoryLabel: 'По категориям: как поступили ведущие проекты',
      categoryLead:
        'Выберите категорию, изучите опубликованные структуры и загрузите любую из них в калькулятор как отправную точку.',
      categoryDefinition: 'Что определяет эту категорию',
      insiderShare: 'средняя доля инсайдеров',
      audited: 'Аудит А8А9',
      publicAudits: 'Все публичные аудиты',
      readAudit: 'Читать публичный аудит',
      allocationLabel: 'Бенчмарки аллокаций по бакетам',
      contextSources: 'Контекст и источники',
      calculatorText:
        'Проверьте собственные числа в калькуляторе. Structure Score сравнит их с похожими запусками.',
      calculator: 'Открыть калькулятор',
      vestingLabel: 'Нормы вестинга',
      trendsLabel: 'Что показывают рыночные данные',
      faq: 'Вопросы и ответы',
      methodology: 'Методология и ограничения',
      openCalculator: 'Открыть в калькуляторе',
      dataNote:
        'Аллокации восстановлены по официальным документам и публичным данным, перепроверены в июле 2026.',
    },
  },
})
