export const eventsMeta = {
  title: 'События — А8А9 токеномика.рф',
  description: 'События, выступления и встречи команды А8А9.',
  ogTitle: 'События — А8А9 токеномика.рф',
  ogDescription: 'События, выступления и встречи команды А8А9.',
} as const

export const eventsContent = {
  title: 'События',
  upcoming: 'Предстоящие',
  past: 'Прошедшие',
  offline: 'Офлайн',
  online: 'Онлайн',
  details: 'Подробнее',
  recordingAvailableAfter: (time: string) => `Запись будет после ${time}`,
  watchRecording: 'Смотреть запись',
  viewPast: 'Посмотреть прошедшие события',
  emptyUpcoming: 'Пока нет предстоящих событий.',
  emptyPast: 'Пока нет прошедших событий.',
  mainOrganizer: 'Главный организатор',
  organizers: 'Организаторы',
  representative: 'Представитель А8А9',
  about: 'О событии',
  summary: 'Саммари встречи',
  location: 'Место',
  openEventSite: 'Открыть сайт мероприятия',
  addToCalendar: 'Добавить в календарь',
  recording: 'Запись доклада',
  presentation: 'Презентация',
  downloadPresentation: 'Скачать презентацию',
  openMap: 'Открыть карту',
  host: 'Хост',
  cohost: 'Ко-хост',
  speaker: 'Спикер',
  profileEvents: (name: string) => `События с ${name}`,
  profileArticles: (name: string) => `Статьи от ${name}`,
} as const
