// Shared UI strings — single source of truth for reusable labels across components

export const uiStrings = {
  learnMore: 'Подробнее',
  read: 'Читать',
  allServices: 'Все услуги',
  allArticles: 'Все статьи',
  readMore: 'Читать ещё',
  minutes: 'мин',
  copyLink: 'Копировать ссылку',
  share: 'Поделиться',
  shareOnX: 'Поделиться в X',
  shareOnFacebook: 'Поделиться в Facebook',
  shareOnTelegram: 'Поделиться в Telegram',
  shareOnLinkedIn: 'Поделиться в LinkedIn',
  tableOfContents: 'Содержание',
  logoAriaLabel: '8Blocks — на главную',
  contactUs: 'Связаться с нами',
  menuOpen: 'Открыть меню',
  menuClose: 'Закрыть меню',
  menuLabel: 'Меню',
  menuCloseLabel: 'Закрыть',
  filterAll: 'Все',
  blogLabel: 'Блог',
  categoryLabel: 'Категория',
  articlesAndInsights: 'Статьи и материалы',
  emptyCategory: 'В этой категории пока нет статей.',
  emptyHint: 'Загляните позже.',
  paginationAriaLabel: 'Навигация по страницам',
  prevPage: 'Предыдущая страница',
  nextPage: 'Следующая страница',
  blogOnTokenomics: 'Блог о токеномике',
  filterByCategory: 'Фильтр по категории',
  seemsLabel: 'Кажется',
  inPracticeLabel: 'На практике',
  whatYouGetAriaLabel: 'Что вы получите',
  solutionAriaLabel: 'Решение',
  auditSolutionAriaLabel: 'Когда нужен аудит',
  partnersAriaLabel: 'Партнёры',
  tokenEconomyAriaLabel: 'Токен-экономика',
  tokenFilterAriaLabel: 'Фильтр токенов',
  ctaAriaLabel: 'Призыв к действию',
  ctaTelegramHref: 'https://t.me/eightblocksio8',
  ctaTelegramLabel: 'Напишите нам в Telegram',
  servicesAriaLabel: 'Услуги',
  aboutAriaLabel: 'О компании',
} as const
