import { siteConfig } from '@/shared/config/site'
import { Container } from '@/shared/ui'
import styles from './PrivacyPolicy.module.scss'

const LAST_UPDATED = 'February 9, 2026'
const COMPANY_ADDRESS =
  '8BLOCKS FZCO, Unit No: UT-12-CO-372, DMCC Business Centre, Level 12, Uptown Tower, Dubai, United Arab Emirates'

export function PrivacyPolicyEn() {
  return (
    <Container>
      <article className={styles.article}>

        <header className={styles.header}>
          <p className={styles.label}>[ Legal Information ]</p>
          <h1 className={styles.title}>Privacy Policy</h1>
          <p className={styles.updated}>Last updated: {LAST_UPDATED}</p>
          <p>
            This Privacy Policy describes our policies and procedures for collecting, using, and
            disclosing your information when you use the Service, and informs you of your privacy
            rights and how the law protects you. We use your personal data to provide and improve
            the Service. By using the Service, you agree to the collection and use of information
            in accordance with this Privacy Policy.
          </p>
        </header>

        <section>
          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            Words with initial capital letters have the meanings defined below. The definitions
            below have the same meaning regardless of whether they appear in the singular or plural.
          </p>
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <dl className={styles.definitions}>
            <div>
              <dt>Account</dt>
              <dd>
                A unique account created for you to access our Service or parts of it.
              </dd>
            </div>
            <div>
              <dt>Affiliate</dt>
              <dd>
                An entity that controls, is controlled by, or is under common control with a party,
                where &quot;control&quot; means ownership of 50% or more of the shares, equity
                interests, or other securities entitled to vote.
              </dd>
            </div>
            <div>
              <dt>Company</dt>
              <dd>
                (referred to as &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or
                &quot;Our&quot; in this document) — {COMPANY_ADDRESS}.
              </dd>
            </div>
            <div>
              <dt>Cookies</dt>
              <dd>
                Small files placed on your computer, mobile device, or any other device by a
                website, containing details of your browsing history and other information.
              </dd>
            </div>
            <div>
              <dt>Country</dt>
              <dd>United Arab Emirates.</dd>
            </div>
            <div>
              <dt>Device</dt>
              <dd>
                Any device that can access the Service, such as a computer, mobile phone, or
                digital tablet.
              </dd>
            </div>
            <div>
              <dt>Personal Data</dt>
              <dd>
                Any information that relates to an identified or identifiable individual.
              </dd>
            </div>
            <div>
              <dt>Service</dt>
              <dd>The website accessible at {siteConfig.url}.</dd>
            </div>
            <div>
              <dt>Service Provider</dt>
              <dd>
                Any natural or legal person who processes data on behalf of the Company. This
                refers to third-party companies or individuals engaged by the Company to facilitate
                the Service, provide the Service on the Company&apos;s behalf, perform services
                related to the Service, or assist the Company in analysing how the Service is used.
              </dd>
            </div>
            <div>
              <dt>Usage Data</dt>
              <dd>
                Data collected automatically, either generated by the use of the Service or from
                the Service infrastructure itself (for example, the duration of a page visit).
              </dd>
            </div>
            <div>
              <dt>You</dt>
              <dd>
                The individual accessing or using the Service, or the company or other legal entity
                on behalf of which such individual is accessing or using the Service.
              </dd>
            </div>
          </dl>
        </section>

        <section>
          <h2>Collection and Use of Personal Data</h2>

          <h3>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>
            While using our Service, we may ask you to provide us with certain personally
            identifiable information that can be used to contact or identify you. Such information
            may include, but is not limited to:
          </p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Usage Data</li>
          </ul>

          <h4>Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service. It may include information
            such as your device&apos;s Internet Protocol (IP) address, browser type and version,
            the pages of our Service that you visit, the date and time of your visit, the time
            spent on those pages, unique device identifiers, and other diagnostic data.
          </p>
          <p>
            When you access the Service via a mobile device, we may automatically collect certain
            information, including the type of mobile device you use, its unique device identifier,
            the IP address of your mobile device, your mobile operating system, the type of mobile
            Internet browser you use, unique device identifiers, and other diagnostic data.
          </p>

          <h3>Tracking Technologies and Cookies</h3>
          <p>
            We use Cookies and similar tracking technologies to track activity on our Service and
            store certain information. The tracking technologies used include beacons, tags, and
            scripts to collect and analyse information and to improve our Service.
          </p>
          <p>
            You can instruct your browser to refuse all Cookies or to indicate when a Cookie is
            being sent. However, if you do not accept Cookies, you may not be able to use some
            parts of our Service. Cookies can be &quot;persistent&quot; or &quot;session&quot;
            Cookies. We use both types for the purposes described below.
          </p>

          <h3>Use of Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li>
              <strong>To provide and maintain our Service</strong>, including monitoring the
              usage of our Service.
            </li>
            <li>
              <strong>To handle your requests</strong>: to attend to and manage requests you
              submit to us.
            </li>
            <li>
              <strong>To contact you</strong>: by email or other equivalent electronic means to
              send updates or informational messages related to features, products, or services.
            </li>
            <li>
              <strong>To send you news and offers</strong>, and other information about similar
              goods, services, and events — unless you have opted out of receiving such information.
            </li>
            <li>
              <strong>For business transfers</strong>: we may use your information to evaluate or
              conduct a merger, restructuring, reorganisation, dissolution, or other sale or
              transfer of some or all of our assets.
            </li>
            <li>
              <strong>For other purposes</strong>: data analysis, identifying usage trends,
              assessing the effectiveness of our marketing campaigns, and evaluating and improving
              our Service and your experience.
            </li>
          </ul>

          <h3>Retention of Personal Data</h3>
          <p>
            The Company will retain your Personal Data only for as long as is necessary for the
            purposes set out in this Privacy Policy. We will retain and use your Personal Data to
            the extent necessary to comply with our legal obligations, resolve disputes, and enforce
            our agreements and policies.
          </p>
          <p>
            Usage Data is generally retained for a shorter period, except where it is used to
            strengthen the security or improve the functionality of our Service, or where we are
            legally obligated to retain it for a longer period.
          </p>

          <h3>Transfer of Personal Data</h3>
          <p>
            Your information, including Personal Data, may be transferred to and maintained on
            computers located outside of your state, province, country, or other governmental
            jurisdiction where the data protection laws may differ from those of your jurisdiction.
          </p>
          <p>
            The Company will take all steps reasonably necessary to ensure that your data is
            treated securely and in accordance with this Privacy Policy. No transfer of your
            Personal Data will take place to an organisation or a country unless there are adequate
            controls in place, including the security of your data.
          </p>

          <h3>Deletion of Personal Data</h3>
          <p>
            You have the right to delete or request that we assist in deleting the Personal Data
            that we have collected about you. Our Service may give you the ability to delete certain
            information about you directly within the Service.
          </p>
          <p>
            You may contact us to request access to, correction of, or deletion of any personal
            information that you have provided to us. Please note that we may need to retain certain
            information when we have a legal obligation or a lawful basis to do so.
          </p>

          <h3>Disclosure of Personal Data</h3>
          <p>
            The Company may disclose your Personal Data if it believes in good faith that such
            action is necessary to:
          </p>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h3>Security of Personal Data</h3>
          <p>
            The security of your Personal Data is important to us, but remember that no method of
            transmission over the Internet or method of electronic storage is 100% secure. While we
            strive to use commercially acceptable means to protect your Personal Data, we cannot
            guarantee its absolute security.
          </p>
        </section>

        <section>
          <h2>Children&apos;s Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 16. We do not knowingly collect
            personally identifiable information from anyone under the age of 16. If you are a parent
            or guardian and you are aware that your child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal Data from anyone under the
            age of 16 without verification of parental consent, we take steps to remove that
            information from our servers.
          </p>
          <p>
            If we need to rely on consent as a legal basis for processing your information and your
            country requires consent from a parent, we may require your parent&apos;s consent before
            we collect and use that information.
          </p>
        </section>

        <section>
          <h2>Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites that are not operated by us. If you
            click on a third-party link, you will be directed to that third party&apos;s site. We
            strongly advise you to review the Privacy Policy of every site you visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content, privacy policies,
            or practices of any third-party sites or services.
          </p>
        </section>

        <section>
          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes
            by posting the new Privacy Policy on this page. We will let you know via email and/or
            a prominent notice on our Service prior to the change becoming effective, and update
            the &quot;Last updated&quot; date at the top of this Policy.
          </p>
          <p>
            We advise you to review this Privacy Policy periodically for any changes. Changes to
            this Privacy Policy are effective when they are posted on this page. This policy was
            last updated on {LAST_UPDATED}.
          </p>
        </section>

        <section>
          <h2>Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, you can contact us by email:
          </p>
          <p>
            <a href={`mailto:${siteConfig.email}`} className={styles.emailLink}>
              {siteConfig.email}
            </a>
          </p>
        </section>

      </article>
    </Container>
  )
}
