export interface CityOption {
  value: string       // slug, e.g. "new-york"
  label: string       // display name, e.g. "New York"
  countryCode: string // ISO 3166-1 alpha-2, e.g. "US"
}

export const EVENT_CITIES: CityOption[] = [
  // ── North America ──────────────────────────────────────────
  { value: 'new-york',          label: 'New York',          countryCode: 'US' },
  { value: 'los-angeles',       label: 'Los Angeles',       countryCode: 'US' },
  { value: 'chicago',           label: 'Chicago',           countryCode: 'US' },
  { value: 'houston',           label: 'Houston',           countryCode: 'US' },
  { value: 'phoenix',           label: 'Phoenix',           countryCode: 'US' },
  { value: 'philadelphia',      label: 'Philadelphia',      countryCode: 'US' },
  { value: 'san-antonio',       label: 'San Antonio',       countryCode: 'US' },
  { value: 'san-diego',         label: 'San Diego',         countryCode: 'US' },
  { value: 'dallas',            label: 'Dallas',            countryCode: 'US' },
  { value: 'san-jose',          label: 'San Jose',          countryCode: 'US' },
  { value: 'austin',            label: 'Austin',            countryCode: 'US' },
  { value: 'san-francisco',     label: 'San Francisco',     countryCode: 'US' },
  { value: 'seattle',           label: 'Seattle',           countryCode: 'US' },
  { value: 'denver',            label: 'Denver',            countryCode: 'US' },
  { value: 'washington-dc',     label: 'Washington D.C.',   countryCode: 'US' },
  { value: 'nashville',         label: 'Nashville',         countryCode: 'US' },
  { value: 'las-vegas',         label: 'Las Vegas',         countryCode: 'US' },
  { value: 'boston',            label: 'Boston',            countryCode: 'US' },
  { value: 'portland',          label: 'Portland',          countryCode: 'US' },
  { value: 'miami',             label: 'Miami',             countryCode: 'US' },
  { value: 'atlanta',           label: 'Atlanta',           countryCode: 'US' },
  { value: 'minneapolis',       label: 'Minneapolis',       countryCode: 'US' },
  { value: 'new-orleans',       label: 'New Orleans',       countryCode: 'US' },
  { value: 'detroit',           label: 'Detroit',           countryCode: 'US' },
  { value: 'charlotte',         label: 'Charlotte',         countryCode: 'US' },
  { value: 'indianapolis',      label: 'Indianapolis',      countryCode: 'US' },
  { value: 'columbus',          label: 'Columbus',          countryCode: 'US' },
  { value: 'raleigh',           label: 'Raleigh',           countryCode: 'US' },
  { value: 'salt-lake-city',    label: 'Salt Lake City',    countryCode: 'US' },
  { value: 'tampa',             label: 'Tampa',             countryCode: 'US' },
  { value: 'orlando',           label: 'Orlando',           countryCode: 'US' },
  { value: 'pittsburgh',        label: 'Pittsburgh',        countryCode: 'US' },
  { value: 'kansas-city',       label: 'Kansas City',       countryCode: 'US' },
  { value: 'sacramento',        label: 'Sacramento',        countryCode: 'US' },
  { value: 'memphis',           label: 'Memphis',           countryCode: 'US' },
  { value: 'baltimore',         label: 'Baltimore',         countryCode: 'US' },
  { value: 'cincinnati',        label: 'Cincinnati',        countryCode: 'US' },
  { value: 'st-louis',          label: 'St. Louis',         countryCode: 'US' },
  { value: 'richmond',          label: 'Richmond',          countryCode: 'US' },
  { value: 'oklahoma-city',     label: 'Oklahoma City',     countryCode: 'US' },
  // Canada
  { value: 'toronto',           label: 'Toronto',           countryCode: 'CA' },
  { value: 'montreal',          label: 'Montreal',          countryCode: 'CA' },
  { value: 'vancouver',         label: 'Vancouver',         countryCode: 'CA' },
  { value: 'calgary',           label: 'Calgary',           countryCode: 'CA' },
  { value: 'edmonton',          label: 'Edmonton',          countryCode: 'CA' },
  { value: 'ottawa',            label: 'Ottawa',            countryCode: 'CA' },
  { value: 'winnipeg',          label: 'Winnipeg',          countryCode: 'CA' },
  { value: 'quebec-city',       label: 'Quebec City',       countryCode: 'CA' },
  // Mexico
  { value: 'mexico-city',       label: 'Mexico City',       countryCode: 'MX' },
  { value: 'guadalajara',       label: 'Guadalajara',       countryCode: 'MX' },
  { value: 'monterrey',         label: 'Monterrey',         countryCode: 'MX' },
  { value: 'cancun',            label: 'Cancún',            countryCode: 'MX' },
  { value: 'tijuana',           label: 'Tijuana',           countryCode: 'MX' },

  // ── South America ──────────────────────────────────────────
  { value: 'sao-paulo',         label: 'São Paulo',         countryCode: 'BR' },
  { value: 'rio-de-janeiro',    label: 'Rio de Janeiro',    countryCode: 'BR' },
  { value: 'brasilia',          label: 'Brasília',          countryCode: 'BR' },
  { value: 'belo-horizonte',    label: 'Belo Horizonte',    countryCode: 'BR' },
  { value: 'buenos-aires',      label: 'Buenos Aires',      countryCode: 'AR' },
  { value: 'cordoba-ar',        label: 'Córdoba',           countryCode: 'AR' },
  { value: 'lima',              label: 'Lima',              countryCode: 'PE' },
  { value: 'bogota',            label: 'Bogotá',            countryCode: 'CO' },
  { value: 'medellin',          label: 'Medellín',          countryCode: 'CO' },
  { value: 'santiago',          label: 'Santiago',          countryCode: 'CL' },
  { value: 'caracas',           label: 'Caracas',           countryCode: 'VE' },
  { value: 'montevideo',        label: 'Montevideo',        countryCode: 'UY' },
  { value: 'quito',             label: 'Quito',             countryCode: 'EC' },
  { value: 'la-paz',            label: 'La Paz',            countryCode: 'BO' },
  { value: 'asuncion',          label: 'Asunción',          countryCode: 'PY' },
  { value: 'panama-city',       label: 'Panama City',       countryCode: 'PA' },
  { value: 'san-jose-cr',       label: 'San José',          countryCode: 'CR' },

  // ── Europe ─────────────────────────────────────────────────
  { value: 'london',            label: 'London',            countryCode: 'GB' },
  { value: 'manchester',        label: 'Manchester',        countryCode: 'GB' },
  { value: 'birmingham',        label: 'Birmingham',        countryCode: 'GB' },
  { value: 'edinburgh',         label: 'Edinburgh',         countryCode: 'GB' },
  { value: 'paris',             label: 'Paris',             countryCode: 'FR' },
  { value: 'lyon',              label: 'Lyon',              countryCode: 'FR' },
  { value: 'marseille',         label: 'Marseille',         countryCode: 'FR' },
  { value: 'bordeaux',          label: 'Bordeaux',          countryCode: 'FR' },
  { value: 'toulouse',          label: 'Toulouse',          countryCode: 'FR' },
  { value: 'nice',              label: 'Nice',              countryCode: 'FR' },
  { value: 'berlin',            label: 'Berlin',            countryCode: 'DE' },
  { value: 'munich',            label: 'Munich',            countryCode: 'DE' },
  { value: 'hamburg',           label: 'Hamburg',           countryCode: 'DE' },
  { value: 'frankfurt',         label: 'Frankfurt',         countryCode: 'DE' },
  { value: 'cologne',           label: 'Cologne',           countryCode: 'DE' },
  { value: 'dusseldorf',        label: 'Düsseldorf',        countryCode: 'DE' },
  { value: 'stuttgart',         label: 'Stuttgart',         countryCode: 'DE' },
  { value: 'madrid',            label: 'Madrid',            countryCode: 'ES' },
  { value: 'barcelona',         label: 'Barcelona',         countryCode: 'ES' },
  { value: 'valencia',          label: 'Valencia',          countryCode: 'ES' },
  { value: 'seville',           label: 'Seville',           countryCode: 'ES' },
  { value: 'bilbao',            label: 'Bilbao',            countryCode: 'ES' },
  { value: 'rome',              label: 'Rome',              countryCode: 'IT' },
  { value: 'milan',             label: 'Milan',             countryCode: 'IT' },
  { value: 'naples',            label: 'Naples',            countryCode: 'IT' },
  { value: 'florence',          label: 'Florence',          countryCode: 'IT' },
  { value: 'turin',             label: 'Turin',             countryCode: 'IT' },
  { value: 'venice',            label: 'Venice',            countryCode: 'IT' },
  { value: 'amsterdam',         label: 'Amsterdam',         countryCode: 'NL' },
  { value: 'rotterdam',         label: 'Rotterdam',         countryCode: 'NL' },
  { value: 'the-hague',         label: 'The Hague',         countryCode: 'NL' },
  { value: 'utrecht',           label: 'Utrecht',           countryCode: 'NL' },
  { value: 'brussels',          label: 'Brussels',          countryCode: 'BE' },
  { value: 'antwerp',           label: 'Antwerp',           countryCode: 'BE' },
  { value: 'ghent',             label: 'Ghent',             countryCode: 'BE' },
  { value: 'vienna',            label: 'Vienna',            countryCode: 'AT' },
  { value: 'graz',              label: 'Graz',              countryCode: 'AT' },
  { value: 'zurich',            label: 'Zurich',            countryCode: 'CH' },
  { value: 'geneva',            label: 'Geneva',            countryCode: 'CH' },
  { value: 'bern',              label: 'Bern',              countryCode: 'CH' },
  { value: 'basel',             label: 'Basel',             countryCode: 'CH' },
  { value: 'lisbon',            label: 'Lisbon',            countryCode: 'PT' },
  { value: 'porto',             label: 'Porto',             countryCode: 'PT' },
  { value: 'stockholm',         label: 'Stockholm',         countryCode: 'SE' },
  { value: 'gothenburg',        label: 'Gothenburg',        countryCode: 'SE' },
  { value: 'malmo',             label: 'Malmö',             countryCode: 'SE' },
  { value: 'oslo',              label: 'Oslo',              countryCode: 'NO' },
  { value: 'bergen',            label: 'Bergen',            countryCode: 'NO' },
  { value: 'copenhagen',        label: 'Copenhagen',        countryCode: 'DK' },
  { value: 'helsinki',          label: 'Helsinki',          countryCode: 'FI' },
  { value: 'prague',            label: 'Prague',            countryCode: 'CZ' },
  { value: 'brno',              label: 'Brno',              countryCode: 'CZ' },
  { value: 'warsaw',            label: 'Warsaw',            countryCode: 'PL' },
  { value: 'krakow',            label: 'Kraków',            countryCode: 'PL' },
  { value: 'wroclaw',           label: 'Wrocław',           countryCode: 'PL' },
  { value: 'gdansk',            label: 'Gdańsk',            countryCode: 'PL' },
  { value: 'poznan',            label: 'Poznań',            countryCode: 'PL' },
  { value: 'budapest',          label: 'Budapest',          countryCode: 'HU' },
  { value: 'bucharest',         label: 'Bucharest',         countryCode: 'RO' },
  { value: 'cluj-napoca',       label: 'Cluj-Napoca',       countryCode: 'RO' },
  { value: 'sofia',             label: 'Sofia',             countryCode: 'BG' },
  { value: 'athens',            label: 'Athens',            countryCode: 'GR' },
  { value: 'thessaloniki',      label: 'Thessaloniki',      countryCode: 'GR' },
  { value: 'dublin',            label: 'Dublin',            countryCode: 'IE' },
  { value: 'cork',              label: 'Cork',              countryCode: 'IE' },
  { value: 'belgrade',          label: 'Belgrade',          countryCode: 'RS' },
  { value: 'zagreb',            label: 'Zagreb',            countryCode: 'HR' },
  { value: 'ljubljana',         label: 'Ljubljana',         countryCode: 'SI' },
  { value: 'bratislava',        label: 'Bratislava',        countryCode: 'SK' },
  { value: 'vilnius',           label: 'Vilnius',           countryCode: 'LT' },
  { value: 'riga',              label: 'Riga',              countryCode: 'LV' },
  { value: 'tallinn',           label: 'Tallinn',           countryCode: 'EE' },
  { value: 'kyiv',              label: 'Kyiv',              countryCode: 'UA' },
  { value: 'lviv',              label: 'Lviv',              countryCode: 'UA' },
  { value: 'kharkiv',           label: 'Kharkiv',           countryCode: 'UA' },
  { value: 'minsk',             label: 'Minsk',             countryCode: 'BY' },
  { value: 'chisinau',          label: 'Chișinău',          countryCode: 'MD' },
  { value: 'tbilisi',           label: 'Tbilisi',           countryCode: 'GE' },
  { value: 'yerevan',           label: 'Yerevan',           countryCode: 'AM' },
  { value: 'baku',              label: 'Baku',              countryCode: 'AZ' },
  { value: 'reykjavik',         label: 'Reykjavik',         countryCode: 'IS' },
  { value: 'valletta',          label: 'Valletta',          countryCode: 'MT' },
  { value: 'nicosia',           label: 'Nicosia',           countryCode: 'CY' },
  { value: 'luxembourg-city',   label: 'Luxembourg City',   countryCode: 'LU' },
  { value: 'monaco',            label: 'Monaco',            countryCode: 'MC' },

  // ── Russia & CIS ───────────────────────────────────────────
  { value: 'moscow',            label: 'Moscow',            countryCode: 'RU' },
  { value: 'saint-petersburg',  label: 'Saint Petersburg',  countryCode: 'RU' },
  { value: 'novosibirsk',       label: 'Novosibirsk',       countryCode: 'RU' },
  { value: 'yekaterinburg',     label: 'Yekaterinburg',     countryCode: 'RU' },
  { value: 'kazan',             label: 'Kazan',             countryCode: 'RU' },
  { value: 'nizhny-novgorod',   label: 'Nizhny Novgorod',   countryCode: 'RU' },
  { value: 'chelyabinsk',       label: 'Chelyabinsk',       countryCode: 'RU' },
  { value: 'samara',            label: 'Samara',            countryCode: 'RU' },
  { value: 'ufa',               label: 'Ufa',               countryCode: 'RU' },
  { value: 'rostov-on-don',     label: 'Rostov-on-Don',     countryCode: 'RU' },
  { value: 'krasnoyarsk',       label: 'Krasnoyarsk',       countryCode: 'RU' },
  { value: 'perm',              label: 'Perm',              countryCode: 'RU' },
  { value: 'volgograd',         label: 'Volgograd',         countryCode: 'RU' },
  { value: 'voronezh',          label: 'Voronezh',          countryCode: 'RU' },
  { value: 'almaty',            label: 'Almaty',            countryCode: 'KZ' },
  { value: 'astana',            label: 'Astana',            countryCode: 'KZ' },
  { value: 'tashkent',          label: 'Tashkent',          countryCode: 'UZ' },
  { value: 'bishkek',           label: 'Bishkek',           countryCode: 'KG' },
  { value: 'dushanbe',          label: 'Dushanbe',          countryCode: 'TJ' },
  { value: 'ashgabat',          label: 'Ashgabat',          countryCode: 'TM' },

  // ── Middle East ────────────────────────────────────────────
  { value: 'dubai',             label: 'Dubai',             countryCode: 'AE' },
  { value: 'abu-dhabi',         label: 'Abu Dhabi',         countryCode: 'AE' },
  { value: 'sharjah',           label: 'Sharjah',           countryCode: 'AE' },
  { value: 'riyadh',            label: 'Riyadh',            countryCode: 'SA' },
  { value: 'jeddah',            label: 'Jeddah',            countryCode: 'SA' },
  { value: 'doha',              label: 'Doha',              countryCode: 'QA' },
  { value: 'kuwait-city',       label: 'Kuwait City',       countryCode: 'KW' },
  { value: 'manama',            label: 'Manama',            countryCode: 'BH' },
  { value: 'muscat',            label: 'Muscat',            countryCode: 'OM' },
  { value: 'tel-aviv',          label: 'Tel Aviv',          countryCode: 'IL' },
  { value: 'jerusalem',         label: 'Jerusalem',         countryCode: 'IL' },
  { value: 'beirut',            label: 'Beirut',            countryCode: 'LB' },
  { value: 'amman',             label: 'Amman',             countryCode: 'JO' },
  { value: 'istanbul',          label: 'Istanbul',          countryCode: 'TR' },
  { value: 'ankara',            label: 'Ankara',            countryCode: 'TR' },
  { value: 'izmir',             label: 'İzmir',             countryCode: 'TR' },
  { value: 'antalya',           label: 'Antalya',           countryCode: 'TR' },
  { value: 'tehran',            label: 'Tehran',            countryCode: 'IR' },
  { value: 'baghdad',           label: 'Baghdad',           countryCode: 'IQ' },

  // ── Africa ─────────────────────────────────────────────────
  { value: 'cairo',             label: 'Cairo',             countryCode: 'EG' },
  { value: 'alexandria',        label: 'Alexandria',        countryCode: 'EG' },
  { value: 'lagos',             label: 'Lagos',             countryCode: 'NG' },
  { value: 'abuja',             label: 'Abuja',             countryCode: 'NG' },
  { value: 'johannesburg',      label: 'Johannesburg',      countryCode: 'ZA' },
  { value: 'cape-town',         label: 'Cape Town',         countryCode: 'ZA' },
  { value: 'durban',            label: 'Durban',            countryCode: 'ZA' },
  { value: 'nairobi',           label: 'Nairobi',           countryCode: 'KE' },
  { value: 'casablanca',        label: 'Casablanca',        countryCode: 'MA' },
  { value: 'rabat',             label: 'Rabat',             countryCode: 'MA' },
  { value: 'marrakech',         label: 'Marrakech',         countryCode: 'MA' },
  { value: 'addis-ababa',       label: 'Addis Ababa',       countryCode: 'ET' },
  { value: 'accra',             label: 'Accra',             countryCode: 'GH' },
  { value: 'dar-es-salaam',     label: 'Dar es Salaam',     countryCode: 'TZ' },
  { value: 'khartoum',          label: 'Khartoum',          countryCode: 'SD' },
  { value: 'tunis',             label: 'Tunis',             countryCode: 'TN' },
  { value: 'algiers',           label: 'Algiers',           countryCode: 'DZ' },
  { value: 'tripoli',           label: 'Tripoli',           countryCode: 'LY' },
  { value: 'abidjan',           label: 'Abidjan',           countryCode: 'CI' },
  { value: 'kampala',           label: 'Kampala',           countryCode: 'UG' },
  { value: 'kinshasa',          label: 'Kinshasa',          countryCode: 'CD' },
  { value: 'luanda',            label: 'Luanda',            countryCode: 'AO' },
  { value: 'dakar',             label: 'Dakar',             countryCode: 'SN' },
  { value: 'maputo',            label: 'Maputo',            countryCode: 'MZ' },
  { value: 'lusaka',            label: 'Lusaka',            countryCode: 'ZM' },
  { value: 'harare',            label: 'Harare',            countryCode: 'ZW' },
  { value: 'antananarivo',      label: 'Antananarivo',      countryCode: 'MG' },

  // ── South & Southeast Asia ─────────────────────────────────
  { value: 'mumbai',            label: 'Mumbai',            countryCode: 'IN' },
  { value: 'delhi',             label: 'Delhi',             countryCode: 'IN' },
  { value: 'bangalore',         label: 'Bangalore',         countryCode: 'IN' },
  { value: 'hyderabad',         label: 'Hyderabad',         countryCode: 'IN' },
  { value: 'chennai',           label: 'Chennai',           countryCode: 'IN' },
  { value: 'kolkata',           label: 'Kolkata',           countryCode: 'IN' },
  { value: 'pune',              label: 'Pune',              countryCode: 'IN' },
  { value: 'ahmedabad',         label: 'Ahmedabad',         countryCode: 'IN' },
  { value: 'karachi',           label: 'Karachi',           countryCode: 'PK' },
  { value: 'lahore',            label: 'Lahore',            countryCode: 'PK' },
  { value: 'islamabad',         label: 'Islamabad',         countryCode: 'PK' },
  { value: 'dhaka',             label: 'Dhaka',             countryCode: 'BD' },
  { value: 'colombo',           label: 'Colombo',           countryCode: 'LK' },
  { value: 'kathmandu',         label: 'Kathmandu',         countryCode: 'NP' },
  { value: 'male',              label: 'Malé',              countryCode: 'MV' },
  { value: 'singapore',         label: 'Singapore',         countryCode: 'SG' },
  { value: 'bangkok',           label: 'Bangkok',           countryCode: 'TH' },
  { value: 'chiang-mai',        label: 'Chiang Mai',        countryCode: 'TH' },
  { value: 'phuket',            label: 'Phuket',            countryCode: 'TH' },
  { value: 'jakarta',           label: 'Jakarta',           countryCode: 'ID' },
  { value: 'bali',              label: 'Bali',              countryCode: 'ID' },
  { value: 'surabaya',          label: 'Surabaya',          countryCode: 'ID' },
  { value: 'kuala-lumpur',      label: 'Kuala Lumpur',      countryCode: 'MY' },
  { value: 'penang',            label: 'Penang',            countryCode: 'MY' },
  { value: 'manila',            label: 'Manila',            countryCode: 'PH' },
  { value: 'cebu',              label: 'Cebu',              countryCode: 'PH' },
  { value: 'ho-chi-minh-city',  label: 'Ho Chi Minh City',  countryCode: 'VN' },
  { value: 'hanoi',             label: 'Hanoi',             countryCode: 'VN' },
  { value: 'da-nang',           label: 'Da Nang',           countryCode: 'VN' },
  { value: 'yangon',            label: 'Yangon',            countryCode: 'MM' },
  { value: 'phnom-penh',        label: 'Phnom Penh',        countryCode: 'KH' },
  { value: 'vientiane',         label: 'Vientiane',         countryCode: 'LA' },

  // ── East Asia ──────────────────────────────────────────────
  { value: 'tokyo',             label: 'Tokyo',             countryCode: 'JP' },
  { value: 'osaka',             label: 'Osaka',             countryCode: 'JP' },
  { value: 'kyoto',             label: 'Kyoto',             countryCode: 'JP' },
  { value: 'yokohama',          label: 'Yokohama',          countryCode: 'JP' },
  { value: 'nagoya',            label: 'Nagoya',            countryCode: 'JP' },
  { value: 'fukuoka',           label: 'Fukuoka',           countryCode: 'JP' },
  { value: 'sapporo',           label: 'Sapporo',           countryCode: 'JP' },
  { value: 'beijing',           label: 'Beijing',           countryCode: 'CN' },
  { value: 'shanghai',          label: 'Shanghai',          countryCode: 'CN' },
  { value: 'shenzhen',          label: 'Shenzhen',          countryCode: 'CN' },
  { value: 'guangzhou',         label: 'Guangzhou',         countryCode: 'CN' },
  { value: 'chengdu',           label: 'Chengdu',           countryCode: 'CN' },
  { value: 'hangzhou',          label: 'Hangzhou',          countryCode: 'CN' },
  { value: 'wuhan',             label: 'Wuhan',             countryCode: 'CN' },
  { value: 'chongqing',         label: 'Chongqing',         countryCode: 'CN' },
  { value: 'xian',              label: "Xi'an",             countryCode: 'CN' },
  { value: 'tianjin',           label: 'Tianjin',           countryCode: 'CN' },
  { value: 'hong-kong',         label: 'Hong Kong',         countryCode: 'HK' },
  { value: 'macau',             label: 'Macau',             countryCode: 'MO' },
  { value: 'taipei',            label: 'Taipei',            countryCode: 'TW' },
  { value: 'seoul',             label: 'Seoul',             countryCode: 'KR' },
  { value: 'busan',             label: 'Busan',             countryCode: 'KR' },
  { value: 'incheon',           label: 'Incheon',           countryCode: 'KR' },
  { value: 'ulaanbaatar',       label: 'Ulaanbaatar',       countryCode: 'MN' },

  // ── Oceania ────────────────────────────────────────────────
  { value: 'sydney',            label: 'Sydney',            countryCode: 'AU' },
  { value: 'melbourne',         label: 'Melbourne',         countryCode: 'AU' },
  { value: 'brisbane',          label: 'Brisbane',          countryCode: 'AU' },
  { value: 'perth',             label: 'Perth',             countryCode: 'AU' },
  { value: 'adelaide',          label: 'Adelaide',          countryCode: 'AU' },
  { value: 'gold-coast',        label: 'Gold Coast',        countryCode: 'AU' },
  { value: 'auckland',          label: 'Auckland',          countryCode: 'NZ' },
  { value: 'wellington',        label: 'Wellington',        countryCode: 'NZ' },
  { value: 'christchurch',      label: 'Christchurch',      countryCode: 'NZ' },
]

/** Быстрый поиск города по slug */
export const EVENT_CITIES_MAP = new Map(EVENT_CITIES.map(c => [c.value, c]))

/** Опции для Payload select-поля */
export const EVENT_CITY_SELECT_OPTIONS = EVENT_CITIES.map(c => ({
  label: c.label,
  value: c.value,
}))
