export const eventsMeta = {
  title: 'Events: Talks, X Spaces & Meetups on Tokenomics',
  description: 'Upcoming and past events with the 8Blocks team: X Spaces, conference talks and meetups on tokenomics, RWA and Web3 business models. Recordings inside.',
  ogTitle: 'Events with the 8Blocks team',
  ogDescription: 'Events, talks, and meetings with the 8Blocks team.',
} as const

export const eventsContent = {
  title: 'Events',
  upcoming: 'Upcoming',
  past: 'Past',
  offline: 'Offline',
  online: 'Online',
  details: 'Details',
  recordingAvailableAfter: (time: string) => `Recording available after ${time}`,
  watchRecording: 'Watch recording',
  viewPast: 'View past events',
  emptyUpcoming: 'No upcoming events yet.',
  emptyPast: 'No past events yet.',
  mainOrganizer: 'Main organizer',
  organizers: 'Organizers',
  representative: '8Blocks representative',
  about: 'About the event',
  summary: 'Meeting summary',
  location: 'Location',
  openEventSite: 'Open event website',
  addToCalendar: 'Add to calendar',
  recording: 'Talk recording',
  presentation: 'Presentation',
  downloadPresentation: 'Download presentation',
  openMap: 'Open map',
  host: 'Host',
  cohost: 'Co-host',
  speaker: 'Speaker',
  profileEvents: (name: string) => `Events with ${name}`,
  profileArticles: (name: string) => `Articles by ${name}`,
} as const
