// Shared UI strings — single source of truth for reusable labels across components

export const uiStrings = {
  learnMore: 'Learn more',
  read: 'Read',
  allServices: 'All services',
  allArticles: 'All articles',
  readMore: 'Read more',
  minutes: 'min',
  copyLink: 'Copy link',
  share: 'Share',
  shareOnX: 'Share on X',
  shareOnFacebook: 'Share on Facebook',
  shareOnTelegram: 'Share on Telegram',
  shareOnLinkedIn: 'Share on LinkedIn',
  tableOfContents: 'Table of contents',
  logoAriaLabel: '8Blocks — go to homepage',
  contactUs: 'Contact us',
  menuOpen: 'Open menu',
  menuClose: 'Close menu',
  menuLabel: 'Menu',
  menuCloseLabel: 'Close',
  filterAll: 'All',
  blogLabel: 'Blog',
  categoryLabel: 'Category',
  articlesAndInsights: 'Articles and insights',
  emptyCategory: 'No articles in this category yet.',
  emptyHint: 'Please check back later.',
  paginationAriaLabel: 'Pagination',
  prevPage: 'Previous page',
  nextPage: 'Next page',
  blogOnTokenomics: 'Blog on token economics',
  filterByCategory: 'Filter by category',
  seemsLabel: 'It seems',
  inPracticeLabel: 'In practice',
  whatYouGetAriaLabel: "What you'll get",
  solutionAriaLabel: 'Solution',
  auditSolutionAriaLabel: 'When an audit is needed',
  partnersAriaLabel: 'Partners',
  tokenEconomyAriaLabel: 'Token economy',
  tokenFilterAriaLabel: 'Token filter',
  ctaAriaLabel: 'Call to action',
  ctaTelegramHref: 'https://t.me/Eight_Blocks',
  ctaTelegramLabel: 'Message us on Telegram',
  servicesAriaLabel: 'Services',
  aboutAriaLabel: 'About the company',
} as const
