import { lang } from '@/shared/i18n'

// Copy stays local to this page; product names and protocol acronyms are retained.
const ru: Record<string, string> = {
  'Limited slots available': 'Количество мест ограничено',
  'Tokenomics AI:': 'ИИ-токеномика:',
  'Your token model. Investor-ready in 48 hours.': 'Ваша токен-модель. Готова для инвесторов за 48 часов.',
  'AI drafts allocations and vesting. The 8Blocks scoring engine flags structural risks and refines the model. You get the refined design and a report for your data room.': 'ИИ создаёт распределение токенов и графики вестинга. Система оценки А8А9 выявляет структурные риски и дорабатывает модель. Вы получаете готовую модель и отчёт для инвесторов.',
  'Request early access': 'Получить ранний доступ',
  'Contact sales': 'Связаться с нами',
  'Early access': 'Ранний доступ',
  'From $299': 'От $299',
  '48h turnaround': 'Готово за 48 часов',
  'Your investor-ready AI model:': 'Ваша ИИ-модель для инвесторов:',
  'AI drafts allocations and vesting': 'ИИ создаёт распределение и вестинг',
  'Refined model': 'Доработанная модель',
  '8 buckets + vesting, tuned against category benchmarks': '8 категорий распределения и вестинг с учётом отраслевых ориентиров',
  'Structure Score': 'Оценка структуры',
  'Shows where your supply structure creates sell pressure, judged against launches like yours': 'Показывает, где структура предложения создаёт давление продаж, в сравнении с похожими запусками',
  'Investor-ready pitch deck': 'Презентация для инвесторов',
  'Branded report ready for your data room in .pdf format': 'Брендированный отчёт для инвесторов в формате PDF',
  'Claim your AI': 'Получите свою',
  'Tokenomics model': 'ИИ-модель токеномики',
  'Allocation chart showing eight buckets totaling 100% of supply': 'Диаграмма распределения: восемь категорий, 100% предложения токенов',
  'Token unlock bars with a cumulative supply curve': 'График разблокировки токенов и кривая совокупного предложения',
  'NOVA Protocol branded tokenomics report preview': 'Пример отчёта по токеномике NOVA Protocol',
  'Close early access form': 'Закрыть форму раннего доступа',
  'Thanks! Your request is in.': 'Спасибо! Заявка отправлена.',
  'We’ll contact you about your project and the next steps.': 'Мы свяжемся с вами, чтобы обсудить проект и следующие шаги.',
  'Done': 'Готово',
  'Email': 'Электронная почта',
  'Project name': 'Название проекта',
  'Your goal': 'Ваша цель',
  'Select a goal': 'Выберите цель',
  'Investor round': 'Инвестиционный раунд',
  'Token launch': 'Запуск токена',
  'Refine an existing model': 'Доработать существующую модель',
  'Explore a token model': 'Изучить токен-модель',
  'Project stage': 'Стадия проекта',
  '(optional)': '(необязательно)',
  'Select a stage': 'Выберите стадию',
  'Pre-seed': 'Предпосевная стадия',
  'Private Sale': 'Закрытый раунд',
  'How did you hear about us?': 'Как вы узнали о нас?',
  'Select a source': 'Выберите источник',
  'Search': 'Поиск',
  'Social media': 'Социальные сети',
  'Referral': 'Рекомендация',
  'Event': 'Мероприятие',
  'Other': 'Другое',
  'We couldn’t send your request. Please try again.': 'Не удалось отправить заявку. Попробуйте ещё раз.',
  'Sending…': 'Отправляем…',
  'Early access starts from $299. We’ll confirm scope and timing with you before payment.': 'Ранний доступ — от $299. До оплаты согласуем с вами объём работы и сроки.',
  'You describe the project': 'Вы описываете проект',
  'Name, sector, stage, goal': 'Название, сектор, стадия, цель',
  'The 8Blocks scoring engine flags structural risks and refines the model. You get the refined design and a report for your data room.': 'Система оценки А8А9 выявляет структурные риски и дорабатывает модель. Вы получаете готовую модель и отчёт для инвесторов.',
  'AI asks what matters': 'ИИ задаёт нужные вопросы',
  'A short dialogue fills the gaps': 'Короткий диалог уточняет детали',
  'Tell us about your planned raise, funding rounds, and any allocations already promised. AI asks the questions a form cannot.': 'Расскажите о планируемых инвестициях, раундах финансирования и уже обещанных долях. ИИ задаст вопросы, которые не предусмотрены в обычной форме.',
  'Model is generated': 'Модель создаётся',
  'Allocations + vesting': 'Распределение и вестинг',
  'AI drafts eight allocation buckets and vesting schedules. The scoring engine tests unlock spikes and refines the model against category benchmarks.': 'ИИ создаёт восемь категорий распределения и графики вестинга. Система оценки проверяет пики разблокировок и дорабатывает модель с учётом отраслевых ориентиров.',
  'You get the package': 'Вы получаете результат',
  'Ready for your data room': 'Всё готово для инвесторов',
  'Your refined model, Structure Score, and branded investor PDF — together in one investor-ready package.': 'Доработанная модель, оценка структуры и брендированный PDF — всё в одном пакете для инвесторов.',
  'How Tokenomics AI works': 'Как работает ИИ-токеномика',
  'Animated preview of the Tokenomics AI product': 'Анимированная демонстрация ИИ-токеномики',
  'Welcome': 'Добро пожаловать',
  'Describe your project': 'Опишите проект',
  'Sector': 'Сектор',
  'Stage': 'Стадия',
  'Funding round': 'Раунд финансирования',
  'Drafting allocations': 'Создаём распределение',
  'Testing unlock spikes': 'Проверяем пики разблокировок',
  'Creating investor PDF': 'Создаём PDF для инвесторов',
  'Your model is ready': 'Ваша модель готова',
  'I need tokenomics for solar panels company': 'Нужна токеномика для компании солнечных панелей',
  'What is your project name?': 'Как называется ваш проект?',
  'Your sector is?': 'В каком секторе вы работаете?',
  'Your stage is?': 'На какой стадии ваш проект?',
  'Planned raise size and rounds?': 'Какой объём инвестиций и какие раунды планируете?',
  '$2M seed, then\na community round': '$2 млн в посевном раунде, затем\nраунд для сообщества',
  'Finance': 'Финансы',
  'Hi there! What’s': 'Привет! Что хотите',
  'on your mind?': 'обсудить?',
  'Drafting 8 allocation buckets...': 'Создаём 8 категорий распределения…',
  'Testing unlock spikes...': 'Проверяем пики разблокировок…',
  'Creating a PDF for your investor...': 'Создаём PDF для вашего инвестора…',
  'Tokenomics': 'Токеномика',
  'DeFi · Pre-seed · $2M': 'DeFi · Предпосевная стадия · $2 млн',
  'Preparing…': 'Готовим…',
  'Download': 'Скачать',
  'illustrative demo PDF': 'демонстрационный PDF',
  'Download failed. Please try again.': 'Не удалось скачать. Попробуйте ещё раз.',
  'Ask anything...': 'Задайте вопрос…',
  'Describe your project...': 'Опишите ваш проект…',
  'Illustrative demo:': 'Демонстрация:',
  '. No live model is being generated.': '. Это пример, а не создание реальной модели.',
  'Play product demo': 'Продолжить демонстрацию',
  'Pause product demo': 'Приостановить демонстрацию',
  '▶ Play': '▶ Продолжить',
  'Ⅱ Pause': 'Ⅱ Пауза',
}

export function copy(text: string): string {
  return lang === 'ru' ? ru[text] ?? text : text
}
